#!/usr/bin/env python3
"""Offline helpers for a curated re:Invent catalog."""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
from datetime import date, datetime
import json
from pathlib import Path
import re
import sys
from typing import Any
from urllib.parse import urlsplit
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


ROOT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- Generated by scripts/reinvent.py render. -->"
GENERATED_PREFIXES = (
    GENERATED + "\n",
    "<!-- Generated by scripts/reinvent.py render. Do not edit this file. -->\n",
)
ID_PATTERN = re.compile(r"[A-Za-z0-9_-]+", re.ASCII)
DATE_PATTERN = re.compile(r"\d{4}-\d{2}-\d{2}", re.ASCII)
REQUIRED_SESSION_FIELDS = (
    "id", "year", "title", "format", "level", "venue", "starts_at",
    "ends_at", "url", "checked_on", "topics", "why_ja",
)
STATUSES = {"candidate", "planned", "reserved", "attended"}


class ValidationError(ValueError):
    """An input file contains invalid or unsafe values."""


def is_year(value: Any) -> bool:
    return type(value) is int and 2000 <= value <= 2100


def is_text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def valid_date(value: Any) -> bool:
    if not isinstance(value, str) or not DATE_PATTERN.fullmatch(value):
        return False
    try:
        date.fromisoformat(value)
    except ValueError:
        return False
    return True


def timezone(value: Any, label: str) -> ZoneInfo:
    if not is_text(value):
        raise ValidationError(f"{label}: IANA タイムゾーンを指定してください")
    try:
        return ZoneInfo(value)
    except (ZoneInfoNotFoundError, ValueError) as exc:
        raise ValidationError(f"{label}: 不明なタイムゾーン {value!r}") from exc


def parse_time(value: Any, label: str) -> datetime | None:
    if value is None:
        return None
    if not isinstance(value, str) or "T" not in value:
        raise ValidationError(f"{label}: オフセット付き ISO 8601 日時か null が必要です")
    try:
        result = datetime.fromisoformat(value)
    except ValueError as exc:
        raise ValidationError(f"{label}: 不正な ISO 8601 日時です") from exc
    if result.tzinfo is None or result.utcoffset() is None:
        raise ValidationError(f"{label}: タイムゾーンのオフセットが必要です")
    return result


def validate_url(value: Any, label: str) -> None:
    if not is_text(value) or any(c.isspace() or ord(c) < 32 for c in value):
        raise ValidationError(f"{label}: 空白を含まない HTTPS URL が必要です")
    try:
        parsed = urlsplit(value)
        port = parsed.port  # Reject malformed or out-of-range ports.
        if (
            parsed.scheme != "https" or not parsed.hostname
            or parsed.username is not None or parsed.password is not None
            or "\\" in value or port == 0
        ):
            raise ValueError("invalid HTTPS URL")
    except ValueError as exc:
        raise ValidationError(f"{label}: 資格情報を含まない絶対 HTTPS URL が必要です") from exc


def validate_catalog(catalog: Any) -> list[str]:
    """Return all recoverable schema errors; unknown metadata is allowed."""
    errors: list[str] = []
    if not isinstance(catalog, dict):
        return ["catalog: JSON オブジェクトが必要です"]
    if type(catalog.get("schema_version")) is not int or catalog.get("schema_version") != 1:
        errors.append("schema_version: 1 が必要です")
    if not valid_date(catalog.get("checked_on")):
        errors.append("checked_on: YYYY-MM-DD 形式の日付が必要です")
    event = catalog.get("event")
    event_zone = None
    if not isinstance(event, dict):
        errors.append("event: JSON オブジェクトが必要です")
    else:
        if not is_year(event.get("year")):
            errors.append("event.year: 2000〜2100 の整数が必要です")
        try:
            event_zone = timezone(event.get("timezone"), "event.timezone")
        except ValidationError as exc:
            errors.append(str(exc))
    sessions = catalog.get("sessions")
    if not isinstance(sessions, list):
        errors.append("sessions: 配列が必要です")
        return errors
    seen: set[tuple[int, str]] = set()
    for index, session in enumerate(sessions):
        label = f"sessions[{index}]"
        if not isinstance(session, dict):
            errors.append(f"{label}: JSON オブジェクトが必要です")
            continue
        for name in REQUIRED_SESSION_FIELDS:
            if name not in session:
                errors.append(f"{label}.{name}: 必須項目です")
        session_id = session.get("id")
        year = session.get("year")
        valid_id = isinstance(session_id, str) and ID_PATTERN.fullmatch(session_id)
        if not valid_id:
            errors.append(f"{label}.id: 英数字・ハイフン・アンダースコアのみ使用できます")
        if not is_year(year):
            errors.append(f"{label}.year: 2000〜2100 の整数が必要です")
        if valid_id and is_year(year):
            key = (year, session_id)
            if key in seen:
                errors.append(f"{label}: year/id が重複しています: {year}/{session_id}")
            seen.add(key)
        for name in ("title", "format", "why_ja"):
            if not is_text(session.get(name)):
                errors.append(f"{label}.{name}: 空でない文字列が必要です")
        if "title_ja" in session and not is_text(session.get("title_ja")):
            errors.append(f"{label}.title_ja: 空でない文字列が必要です")
        level = session.get("level")
        if level is not None and not (is_text(level) or type(level) is int):
            errors.append(f"{label}.level: 文字列・整数・null のいずれかが必要です")
        venue = session.get("venue")
        if venue is not None and not is_text(venue):
            errors.append(f"{label}.venue: 空でない文字列か null が必要です")
        if not valid_date(session.get("checked_on")):
            errors.append(f"{label}.checked_on: YYYY-MM-DD 形式の日付が必要です")
        topics = session.get("topics")
        if not isinstance(topics, list) or not all(is_text(topic) for topic in topics):
            errors.append(f"{label}.topics: 空でない文字列の配列が必要です")
        try:
            validate_url(session.get("url"), f"{label}.url")
        except ValidationError as exc:
            errors.append(str(exc))
        times = {}
        for name in ("starts_at", "ends_at"):
            try:
                timestamp = parse_time(session.get(name), f"{label}.{name}")
                times[name] = timestamp
                if timestamp is not None and is_year(year):
                    local_time = timestamp.astimezone(event_zone) if event_zone else timestamp
                    if local_time.year != year:
                        errors.append(f"{label}.{name}: 日時の年が session.year と一致しません")
            except ValidationError as exc:
                errors.append(str(exc))
        start, end = times.get("starts_at"), times.get("ends_at")
        if end is not None and "starts_at" in times and start is None:
            errors.append(f"{label}: ends_at がある場合は starts_at も必要です")
        if start is not None and end is not None and end <= start:
            errors.append(f"{label}.ends_at: 開始日時より後である必要があります")
    return errors


def require_valid_catalog(catalog: Any) -> dict[str, Any]:
    errors = validate_catalog(catalog)
    if errors:
        raise ValidationError("\n".join(errors))
    return catalog


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ValidationError(f"{path}: JSON を読み込めません: {exc}") from exc


def escape_md(value: Any) -> str:
    text = str(value).replace("\r", " ").replace("\n", " ")
    return re.sub(r"([\\`*_{}\[\]()<>#+.!|])", r"\\\1", text)


def source_link(url: str) -> str:
    return f"[公式ページ](<{url.replace('<', '%3C').replace('>', '%3E')}>)"


def display_time(value: str | None, zone: ZoneInfo) -> str:
    if value is None:
        return "未確認"
    return datetime.fromisoformat(value).astimezone(zone).strftime("%Y-%m-%d %H:%M %Z")


def render_catalog(catalog: Any, root: Path) -> list[Path]:
    """Render owned files only, preserving all notes and hand-written files."""
    catalog = require_valid_catalog(catalog)
    root = root.resolve()
    zone = timezone(catalog["event"]["timezone"], "event.timezone")
    ordered = sorted(catalog["sessions"], key=lambda s: (s["year"], s["id"]))
    lines = [
        GENERATED, "", "# セッション候補カタログ", "",
        "編集元は `data/catalog.json`。メモは `notes/`。", "",
        f"確認日: {catalog['checked_on']}。日時は `{catalog['event']['timezone']}`。", "",
        "| 年 / ID | セッション | 形式 | レベル | 開始 | 会場 |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    output: dict[Path, str] = {}
    for session in ordered:
        year, session_id = session["year"], session["id"]
        title = escape_md(session["title"])
        title_ja = session.get("title_ja")
        session_format = escape_md(session["format"])
        level = escape_md(session["level"] if session["level"] is not None else "未確認")
        venue = escape_md(session["venue"] or "未確認")
        starts = display_time(session["starts_at"], zone)
        ends = display_time(session["ends_at"], zone)
        lines.append(
            f"| {year} / {session_id} | [{title}](../sessions/{year}/{session_id}/README.md) "
            f"| {session_format} | {level} | {starts} | {venue} |"
        )
        session_lines = [
            GENERATED, "", f"# {session_id}: {title}", "",
        ]
        if is_text(title_ja):
            session_lines.extend([escape_md(title_ja), ""])
        session_lines.extend([
            "メモは `notes/`。", "",
            "| 項目 | 内容 |", "| --- | --- |",
            f"| 年 | {year} |", f"| 形式 | {session_format} |", f"| レベル | {level} |",
            f"| 会場 | {venue} |", f"| 開始 | {starts} |", f"| 終了 | {ends} |",
            f"| 確認日 | {session['checked_on']} |",
            f"| 出典 | {source_link(session['url'])} |", "",
            "## 候補にした理由", "", escape_md(session["why_ja"]), "",
            "## トピック", "",
            ", ".join(escape_md(topic) for topic in session["topics"]) or "未設定", "",
        ])
        output[root / "sessions" / str(year) / session_id / "README.md"] = "\n".join(session_lines)
    output[root / "docs" / "catalog.md"] = "\n".join(lines) + "\n"
    # Preflight before writing, including symlinks and pre-existing personal text.
    for path in output:
        if not path.resolve().is_relative_to(root):
            raise ValidationError(f"{path}: 出力先がリポジトリの外です")
        if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_PREFIXES):
            raise ValidationError(f"{path}: 自動生成マーカーがないため上書きしません")
    for path, content in output.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return list(output)


EVENT_CATEGORIES = dict(keynote="基調講演", party="パーティー", reception="レセプション", expo="Expo",
                        activity="アクティビティ", community="コミュニティ", japan="日本向け", other="その他")
EVENT_REGISTRATION = dict(none="不要", required="必要", unknown="未確認")
EVENT_INTENT = {"go": "行く", "maybe": "検討", "skip": "見送り", None: "—"}
SLUG_PATTERN = re.compile(r"[a-z0-9-]+", re.ASCII)
EVENT_FIELDS = ("id", "title", "title_ja", "category", "date", "starts_at", "ends_at", "venue",
                "registration", "url", "checked_on", "note_ja", "intent")


def validate_events(data: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(data, dict):
        return ["events: JSON オブジェクトが必要です"]
    if type(data.get("schema_version")) is not int or data.get("schema_version") != 1:
        errors.append("schema_version: 1 が必要です")
    if not valid_date(data.get("checked_on")):
        errors.append("checked_on: YYYY-MM-DD 形式の日付が必要です")
    zone = None
    try:
        zone = timezone(data.get("timezone"), "timezone")
    except ValidationError as exc:
        errors.append(str(exc))
    for collection, fields in (("sources", ("id", "url", "label_ja")), ("events", EVENT_FIELDS)):
        entries = data.get(collection)
        if not isinstance(entries, list):
            errors.append(f"{collection}: 配列が必要です")
            continue
        seen = set()
        for index, entry in enumerate(entries):
            label = f"{collection}[{index}]"
            if not isinstance(entry, dict):
                errors.append(f"{label}: JSON オブジェクトが必要です")
                continue
            for name in fields:
                if name not in entry:
                    errors.append(f"{label}.{name}: 必須項目です")
            entry_id = entry.get("id")
            if not isinstance(entry_id, str) or not SLUG_PATTERN.fullmatch(entry_id):
                errors.append(f"{label}.id: 小文字英数字・ハイフンのみ使用できます")
            elif entry_id in seen:
                errors.append(f"{label}.id: ID が重複しています: {entry_id}")
            else:
                seen.add(entry_id)
            try:
                validate_url(entry.get("url"), f"{label}.url")
            except ValidationError as exc:
                errors.append(str(exc))
            for name in (("label_ja",) if collection == "sources" else ("title",)):
                if not is_text(entry.get(name)):
                    errors.append(f"{label}.{name}: 空でない文字列が必要です")
            if collection == "sources":
                continue
            for name in ("title_ja", "venue", "note_ja", "public_note_ja"):
                if entry.get(name) is not None and not is_text(entry[name]):
                    errors.append(f"{label}.{name}: 空でない文字列か null が必要です")
            for name, allowed in (("category", EVENT_CATEGORIES), ("registration", EVENT_REGISTRATION), ("intent", EVENT_INTENT)):
                value = entry.get(name)
                if not isinstance(value, (str, type(None))) or value not in allowed:
                    errors.append(f"{label}.{name}: 有効な値が必要です")
            for name in ("date", "checked_on"):
                if (name == "checked_on" or entry.get(name) is not None) and not valid_date(entry.get(name)):
                    errors.append(f"{label}.{name}: YYYY-MM-DD 形式の日付が必要です")
            times = {}
            for name in ("starts_at", "ends_at"):
                try:
                    times[name] = parse_time(entry.get(name), f"{label}.{name}")
                except ValidationError as exc:
                    errors.append(str(exc))
            start, end = times.get("starts_at"), times.get("ends_at")
            if start is not None and zone is not None and entry.get("date") != start.astimezone(zone).date().isoformat():
                errors.append(f"{label}.date: 開始日時の現地日付と一致する必要があります")
            if end is not None and start is None:
                errors.append(f"{label}.starts_at: 終了日時がある場合は開始日時が必要です")
            if start is not None and end is not None and end <= start:
                errors.append(f"{label}.ends_at: 開始日時より後である必要があります")
    return errors


def require_valid_events(data: Any) -> dict[str, Any]:
    errors = validate_events(data)
    if errors:
        raise ValidationError("\n".join(errors))
    return data


def event_relation(event: dict[str, Any], sessions: list[dict[str, Any]], transfer: int) -> str:
    start = parse_time(event["starts_at"], "starts_at")
    end = parse_time(event["ends_at"], "ends_at")
    if start is None:
        return "—"
    overlaps, transfers = [], []
    for session in sessions:
        other_start = parse_time(session["starts_at"], "starts_at")
        other_end = parse_time(session["ends_at"], "ends_at")
        if other_start is None or other_end is None:
            continue
        if end is not None and start < other_end and other_start < end:
            overlaps.append(session["id"])
        elif event["venue"] and session["venue"] and event["venue"] != session["venue"]:
            gap = None
            if start >= other_end:
                gap = (start - other_end).total_seconds() / 60
            elif end is not None and other_start >= end:
                gap = (other_start - end).total_seconds() / 60
            if gap is not None and gap < transfer:
                transfers.append(session["id"])
    if overlaps:
        return "重なる: " + ", ".join(sorted(set(overlaps)))
    if transfers:
        return "移動注意: " + ", ".join(sorted(set(transfers)))
    return "なし"


def render_events(data: Any, catalog: Any, schedule: Any, root: Path) -> Path:
    data = require_valid_events(data)
    check_schedule(catalog, schedule)
    zone = timezone(data["timezone"], "timezone")
    keys = {(item["year"], item["id"]) for item in schedule["items"] if item["status"] in {"planned", "reserved"}}
    sessions = [s for s in catalog["sessions"] if (s["year"], s["id"]) in keys]
    lines = [GENERATED, "", "# イベント一覧", "",
             f"編集元は `data/events.json`。確認日: {data['checked_on']}。日時は `{data['timezone']}`。"]
    def order(entry):
        start = parse_time(entry["starts_at"], "starts_at")
        return (entry["date"] or "9999-99-99", start is None,
                start.timestamp() if start else 0, entry["id"])
    previous = object()
    for entry in sorted(data["events"], key=order):
        day = entry["date"]
        if day != previous:
            heading = "日付未定" if day is None else f"{day}（{'月火水木金土日'[date.fromisoformat(day).weekday()]}）"
            lines.extend(["", f"## {heading}", "", "| 時間 | イベント | 種類 | 会場 | 登録 | 予定 | 予約との関係 | メモ |",
                          "| --- | --- | --- | --- | --- | --- | --- | --- |"])
            previous = day
        start = parse_time(entry["starts_at"], "starts_at")
        end = parse_time(entry["ends_at"], "ends_at")
        clock = "時刻未定" if start is None else start.astimezone(zone).strftime("%H:%M")
        if start is not None and end is not None:
            clock += "–" + end.astimezone(zone).strftime("%H:%M")
        title = escape_md(entry["title_ja"] or entry["title"])
        if entry["title_ja"]:
            title += "（" + escape_md(entry["title"]) + "）"
        url = entry["url"].replace("<", "%3C").replace(">", "%3E")
        cells = [clock, f"[{title}](<{url}>)", EVENT_CATEGORIES[entry["category"]], escape_md(entry["venue"] or "未確認"),
                 EVENT_REGISTRATION[entry["registration"]], EVENT_INTENT[entry["intent"]],
                 escape_md(event_relation(entry, sessions, schedule["transfer_minutes"])), escape_md(entry["note_ja"] or "—")]
        lines.append("| " + " | ".join(cells) + " |")
    lines.extend(["", "## 出典", ""])
    for source in data["sources"]:
        url = source["url"].replace("<", "%3C").replace(">", "%3E")
        lines.append(f"- [{escape_md(source['label_ja'])}](<{url}>)")
    path = root.resolve() / "docs" / "events.md"
    if not path.resolve().is_relative_to(root.resolve()):
        raise ValidationError(f"{path}: 出力先がリポジトリの外です")
    if path.exists() and not path.read_text(encoding="utf-8").startswith(GENERATED_PREFIXES):
        raise ValidationError(f"{path}: 自動生成マーカーがないため上書きしません")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return path


@dataclass
class ScheduleReport:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    checked: int = 0


def check_schedule(catalog: Any, schedule: Any, events: Any = None) -> ScheduleReport:
    catalog = require_valid_catalog(catalog)
    if not isinstance(schedule, dict):
        raise ValidationError("schedule: JSON オブジェクトが必要です")
    zone = timezone(schedule.get("timezone"), "schedule.timezone")
    transfer = schedule.get("transfer_minutes")
    if type(transfer) is not int or transfer < 0:
        raise ValidationError("schedule.transfer_minutes: 0 以上の整数が必要です")
    items = schedule.get("items")
    if not isinstance(items, list):
        raise ValidationError("schedule.items: 配列が必要です")
    sessions = {(s["year"], s["id"]): s for s in catalog["sessions"]}
    seen: set[tuple[int, str]] = set()
    active = []
    report = ScheduleReport()
    for index, item in enumerate(items):
        label = f"schedule.items[{index}]"
        if not isinstance(item, dict):
            raise ValidationError(f"{label}: JSON オブジェクトが必要です")
        session_id, year = item.get("id"), item.get("year")
        if not isinstance(session_id, str) or not ID_PATTERN.fullmatch(session_id) or not is_year(year):
            raise ValidationError(f"{label}: 有効な year と id が必要です")
        key = (year, session_id)
        if key in seen:
            raise ValidationError(f"{label}: year/id が重複しています: {year}/{session_id}")
        seen.add(key)
        if key not in sessions:
            raise ValidationError(f"{label}: カタログにないセッションです: {year}/{session_id}")
        if not isinstance(item.get("status"), str) or item["status"] not in STATUSES:
            raise ValidationError(f"{label}.status: candidate/planned/reserved/attended のいずれかが必要です")
        if "review_ja" in item and item["review_ja"] is not None and not is_text(item["review_ja"]):
            raise ValidationError(f"{label}.review_ja: 空でない文字列か null が必要です")
        if item["status"] not in {"planned", "reserved"}:
            continue
        session = sessions[key]
        display_id = f"{year}/{session_id}"
        start = parse_time(session["starts_at"], f"{display_id}.starts_at")
        end = parse_time(session["ends_at"], f"{display_id}.ends_at")
        if not session["venue"]:
            report.warnings.append(f"{display_id}: 会場未確認のため移動時間を完全には確認できません")
        if start is None or end is None:
            report.warnings.append(f"{display_id}: 開始・終了時刻が未確定のため時間の競合を確認できません")
            continue
        active.append((start, end, display_id, session["venue"]))
    if events is not None:
        events = require_valid_events(events)
        for event in events["events"]:
            if event["intent"] != "go" or event["starts_at"] is None:
                continue
            display_id = f"event:{event['id']}"
            start = parse_time(event["starts_at"], f"{display_id}.starts_at")
            end = parse_time(event["ends_at"], f"{display_id}.ends_at")
            if end is None:
                report.warnings.append(f"{display_id}: 開始・終了時刻が未確定のため時間の競合を確認できません")
                continue
            active.append((start, end, display_id, event["venue"]))
    active.sort(key=lambda entry: (entry[0], entry[1], entry[2]))
    report.checked = len(active)
    for i, current in enumerate(active):
        for previous in active[:i]:
            if current[0] < previous[1]:
                report.errors.append(
                    f"時間重複: {previous[2]} → {current[2]} "
                    f"({current[0].astimezone(zone).strftime('%m-%d %H:%M %Z')})"
                )
        if i == 0:
            continue
        previous = active[i - 1]
        if previous[3] and current[3] and previous[3] != current[3] and current[0] >= previous[1]:
            gap = (current[0] - previous[1]).total_seconds() / 60
            if gap < transfer:
                report.errors.append(
                    f"移動時間不足: {previous[2]} → {current[2]} は {gap:g} 分 "
                    f"(異なる会場には {transfer} 分を設定)"
                )
    return report


def search_catalog(catalog: Any, keyword: str) -> list[dict[str, Any]]:
    catalog = require_valid_catalog(catalog)
    term = keyword.casefold()
    return [
        session for session in sorted(catalog["sessions"], key=lambda s: (s["year"], s["id"]))
        if term in " ".join(str(value) for value in session.values()).casefold()
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, default=ROOT / "data" / "catalog.json")
    parser.add_argument("--events", type=Path, default=ROOT / "data" / "events.json")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("validate", help="カタログの形式を検証")
    search = commands.add_parser("search", help="候補をキーワードで検索")
    search.add_argument("keyword")
    commands.add_parser("render", help="カタログとセッション Markdown を再生成")
    schedule = commands.add_parser("check-schedule", help="予定の重複と移動時間を検証")
    schedule.add_argument("path", nargs="?", type=Path, default=ROOT / "planning" / "schedule.json")
    watch = commands.add_parser("watch-events", help="公式イベント情報の差分を取得")
    watch.add_argument("--source")
    for command in (commands.choices["validate"], commands.choices["render"], schedule, watch):
        command.add_argument("--events", type=Path, default=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        if args.command == "watch-events":
            if __package__:
                from .event_watch import watch_events
            else:
                from event_watch import watch_events
            return watch_events(require_valid_events(read_json(args.events))["sources"], source=args.source)
        catalog = require_valid_catalog(read_json(args.catalog))
        events = require_valid_events(read_json(args.events)) if args.command != "search" else None
        if args.command == "validate":
            print(f"OK: {len(catalog['sessions'])} セッション / {len(events['events'])} イベントを検証しました")
        elif args.command == "search":
            found = search_catalog(catalog, args.keyword)
            for session in found:
                print(f"{session['year']}/{session['id']} [{session['format']}] {session['title']}")
                print(f"  {session['url']}")
            print(f"{len(found)} 件")
        elif args.command == "render":
            paths = render_catalog(catalog, ROOT)
            paths.append(render_events(events, catalog, read_json(ROOT / "planning" / "schedule.json"), ROOT))
            print(f"OK: {len(paths)} ファイルを生成しました")
        elif args.command == "check-schedule":
            report = check_schedule(catalog, read_json(args.path), events)
            for message in report.warnings:
                print(f"WARN: {message}")
            for message in report.errors:
                print(f"ERROR: {message}")
            print(f"確認済み: {report.checked} 件 / エラー: {len(report.errors)} / 注意: {len(report.warnings)}")
            if report.errors:
                return 1
        return 0
    except (ValidationError, OSError, UnicodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
